# Generated by Django 4.2.2 on 2024-10-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_producto_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('advice', models.BooleanField(verbose_name='Advice')),
            ],
        ),
        migrations.CreateModel(
            name='QueryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='Descriptiom')),
                ('image', models.ImageField(null=True, upload_to='img/service', verbose_name='Service image')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='TipoConsulta',
        ),
        migrations.AddField(
            model_name='contact',
            name='query_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.querytype', verbose_name='Query Type'),
        ),
    ]
